name: fitnessapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.1.0
  pedometer: ^3.0.0
  device_preview: ^1.1.0
  responsive_framework: ^0.2.0
  flutter_gifimage: ^1.0.1
  page_view_indicators: ^2.0.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^3.4.4
  modal_progress_hud: ^0.1.3
  cron: ^0.5.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  jiffy: ^5.0.0
  intl: ^0.17.0
  flutter_countdown_timer: ^4.1.0
  webview_flutter: ^3.0.4
  day_picker: ^2.1.1
  flutter_custom_dialog: ^1.0.20
  permission_handler: ^10.0.0
  flutter_spinkit: ^5.1.0
  flutter_storage: ^0.9.4
  toast: ^0.3.0
  file_picker: ^5.0.1
  # flutter_full_pdf_viewer: ^1.0.6
  firebase_storage: ^10.0.1
  path_provider: ^2.0.2
  flutter_local_notifications: ^9.7.1
  plugin_platform_interface: ^2.0.1
  flutter_local_notifications_platform_interface: ^5.0.0
  platform: ^3.0.0
  timezone: ^0.8.0
  device_info: ^2.0.2
  health: ^4.1.1
  # wifi_flutter: ^0.1.0
  # jitsi_meet: ^4.0.0
  shared_preferences: ^2.0.6
  firebase_messaging: ^12.0.2
  # flutter_full_pdf_viewer: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/beginner_plan.jpg
    - images/abs_ex.jpg
    - images/advance_plan.jpg
    - images/arm_ex.jpg
    - images/cards_back.png
    - images/chest_ex.jpg
    - images/donevector.jpg
    - images/gfit_header.png
    - images/graph_avatar.png
    - images/inter_plan.jpg
    - images/jumping_jack.gif
    - images/jumping_jack2.gif
    - images/leg_ex.jpg
    - images/minerva_tp.png
    - images/minerva.jpg
    - images/mytrainees.jpg
    - images/onboardsplash1.png
    - images/onboardsplash2.png
    - images/onboardsplash3.png
    - images/profile_avatar.png
    - images/profile_trainer.jpg
    - images/runner_avatar.png
    - images/shoulder_back_ex.jpg
    - images/test.gif
    - images/trainer_head.jpg
    - images/water_avatar.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
